### ISSUE TITLE
Flaky test: DefaultDnsClientTest.repeatDiscoverNxDomain

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#1102]
https://ci.servicetalk.io/job/servicetalk-java8-prb/1450/testReport/junit/io.servicetalk.dns.discovery.netty/DefaultDnsClientTest/repeatDiscoverNxDomain/

```
Regression
io.servicetalk.dns.discovery.netty.DefaultDnsClientTest.repeatDiscoverNxDomain

Error Message
java.lang.AssertionError: Unexpected exception during DNS lookup.
Expected: an instance of java.net.UnknownHostException
     but: null
Stacktrace
java.lang.AssertionError: Unexpected exception during DNS lookup.
Expected: an instance of java.net.UnknownHostException
     but: null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.servicetalk.dns.discovery.netty.DefaultDnsClientTest.repeatDiscoverNxDomain(DefaultDnsClientTest.java:478)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:171)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by idelpivnitskiy** [comment]
https://ci.servicetalk.io/job/servicetalk-transport-observability-java8-prb/55/testReport/junit/io.servicetalk.dns.discovery.netty/DefaultDnsClientTest/repeatDiscoverNxDomain/

with the same stack trace
