### ISSUE TITLE
BufferStrategiesTest.sizeOrDurationConcurrent test failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#1259]
https://github.com/apple/servicetalk/runs/1521278514

```
2020-12-09T01:47:11.8036134Z     "Time-limited test" #41 waiting on java.util.concurrent.CountDownLatch$Sync@27c94c64
2020-12-09T01:47:11.8037423Z       java.lang.Thread.State: WAITING
2020-12-09T01:47:11.8038496Z     	  at java.base@11.0.9/jdk.internal.misc.Unsafe.park(Native Method)
2020-12-09T01:47:11.8040231Z     	  at java.base@11.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
2020-12-09T01:47:11.8044291Z     	  at java.base@11.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
2020-12-09T01:47:11.8050637Z     	  at java.base@11.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
2020-12-09T01:47:11.8086901Z     	  at java.base@11.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
2020-12-09T01:47:11.8091154Z     	  at java.base@11.0.9/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
2020-12-09T01:47:11.8095061Z     	  at app//io.servicetalk.concurrent.api.BufferStrategiesTest.sizeOrDurationConcurrent(BufferStrategiesTest.java:117)
2020-12-09T01:47:11.8099116Z     	  at java.base@11.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-09T01:47:11.8131797Z     	  at java.base@11.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-09T01:47:11.8135694Z     	  at java.base@11.0.9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-09T01:47:11.8138297Z     	  at java.base@11.0.9/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-09T01:47:11.8140151Z     	  at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2020-12-09T01:47:11.8142993Z     	  at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2020-12-09T01:47:11.8147789Z     	  at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2020-12-09T01:47:11.8150667Z     	  at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2020-12-09T01:47:11.8153366Z     	  at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2020-12-09T01:47:11.8156781Z     	  at app//io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:171)
2020-12-09T01:47:11.8169370Z     	  at app//io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:163)
2020-12-09T01:47:11.8172489Z     	  at java.base@11.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-12-09T01:47:11.8174123Z     	  at java.base@11.0.9/java.lang.Thread.run(Thread.java:834)
```

**Comment by idelpivnitskiy** [comment]
With the attached patch I was able to get more info of the state that deadlocks:
```
    boundaries: 0
    boundariesToFinish: 369
    pending timers: 0
    boundariesReceived: 369
    state: java.lang.Object@5d81bb51
    java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at io.servicetalk.concurrent.api.BufferStrategiesTest.sizeOrDurationConcurrent(BufferStrategiesTest.java:145)


...
    "servicetalk-executor-1-1" #16 waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7f9735cd
      java.lang.Thread.State: WAITING
          at sun.misc.Unsafe.park(Native Method)
          at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
          at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
          at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
          at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
          at io.servicetalk.concurrent.api.BufferStrategiesTest.lambda$sizeOrDurationConcurrent$2(BufferStrategiesTest.java:122)
          at io.servicetalk.concurrent.api.BufferStrategiesTest$$Lambda$368/1945318547.call(Unknown Source)
          at io.servicetalk.concurrent.api.AbstractSubmitSingle.lambda$handleSubscribe$0(AbstractSubmitSingle.java:44)
          at io.servicetalk.concurrent.api.AbstractSubmitSingle$$Lambda$369/1319563239.run(Unknown Source)
          at io.servicetalk.concurrent.api.ContextPreservingRunnable.run(ContextPreservingRunnable.java:43)
          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
          at java.lang.Thread.run(Thread.java:748)

          Number of locked synchronizers = 1
          - java.util.concurrent.ThreadPoolExecutor$Worker@57d96542

    "servicetalk-executor-1-2" #17 waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@aa3974b
      java.lang.Thread.State: WAITING
          at sun.misc.Unsafe.park(Native Method)
          at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
          at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
          at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
          at io.servicetalk.concurrent.api.BufferStrategiesTest.lambda$sizeOrDurationConcurrent$3(BufferStrategiesTest.java:131)
          at io.servicetalk.concurrent.api.BufferStrategiesTest$$Lambda$371/1244734728.call(Unknown Source)
          at io.servicetalk.concurrent.api.AbstractSubmitSingle.lambda$handleSubscribe$0(AbstractSubmitSingle.java:44)
          at io.servicetalk.concurrent.api.AbstractSubmitSingle$$Lambda$369/1319563239.run(Unknown Source)
          at io.servicetalk.concurrent.api.ContextPreservingRunnable.run(ContextPreservingRunnable.java:43)
          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
          at java.lang.Thread.run(Thread.java:748)

          Number of locked synchronizers = 1
          - java.util.concurrent.ThreadPoolExecutor$Worker@1deffa02

```
So, the test thread blocks at `boundariesDone` and two other threads block at attempt to take the next items from the corresponding queues. Still don't understand why this situation happens. From my understanding, the `timers` queue` should also have more items when we accumulate a new item. Will leave these intermediate notes here for records.

Patch:
```patch
Index: servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/BufferStrategiesTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/BufferStrategiesTest.java b/servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/BufferStrategiesTest.java
--- a/servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/BufferStrategiesTest.java	(revision d1d008ff9a19a8364e5114efcbcbf8edc79576f7)
+++ b/servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/BufferStrategiesTest.java	(date 1626154006629)
@@ -20,10 +20,12 @@
 import io.servicetalk.concurrent.PublisherSource.Subscription;
 import io.servicetalk.concurrent.api.BufferStrategy.Accumulator;
 import io.servicetalk.concurrent.internal.TerminalNotification;
+import io.servicetalk.concurrent.internal.TimeoutTracingInfoExtension;
 
 import org.hamcrest.Matchers;
-import org.junit.jupiter.api.Disabled;
+import org.junit.jupiter.api.RepeatedTest;
 import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.Timeout;
 import org.junit.jupiter.api.extension.RegisterExtension;
 
 import java.time.Duration;
@@ -81,8 +83,11 @@
     @RegisterExtension
     static final ExecutorExtension<TestExecutor> TEST_EXECUTOR_EXTENSION = withTestExecutor();
 
-    @Test
-    @Disabled("https://github.com/apple/servicetalk/issues/1259")
+    @RegisterExtension
+    static final TimeoutTracingInfoExtension DUMP = new TimeoutTracingInfoExtension();
+
+    @Timeout(10)
+    @RepeatedTest(1)
     void sizeOrDurationConcurrent() throws Exception {
         final BlockingQueue<TestCompletable> timers = new LinkedBlockingDeque<>();
         final Executor executor = mock(Executor.class);
@@ -101,51 +106,60 @@
         CountDownLatch boundariesDone = new CountDownLatch(1);
         BlockingQueue<Accumulator<Integer, Iterable<Integer>>> boundaries = new LinkedBlockingQueue<>();
         BlockingQueue<Accumulator<Integer, Iterable<Integer>>> boundariesToFinish = new LinkedBlockingQueue<>();
+        AtomicInteger boundariesReceived = new AtomicInteger();
 
-        strategy.boundaries()
-                .beforeOnNext(boundaries::add)
-                .takeAtMost(maxBoundaries)
-                .afterFinally(boundariesDone::countDown)
-                .ignoreElements().subscribe();
-        CyclicBarrier accumulateAndTimerStarted = new CyclicBarrier(2);
+        try {
+            strategy.boundaries()
+                    .beforeOnNext(boundaries::add)
+                    .takeAtMost(maxBoundaries)
+                    .afterFinally(boundariesDone::countDown)
+                    .ignoreElements().subscribe();
+            CyclicBarrier accumulateAndTimerStarted = new CyclicBarrier(2);
 
-        Future<Object> timersFuture = EXECUTOR_EXTENSION.executor().submit(() -> {
-            accumulateAndTimerStarted.await();
-            while (boundariesDone.getCount() > 0) {
-                timers.take().onComplete();
-            }
-            return null;
-        }).toFuture();
+            Future<Object> timersFuture = EXECUTOR_EXTENSION.executor().submit(() -> {
+                accumulateAndTimerStarted.await();
+                while (boundariesDone.getCount() > 0) {
+                    timers.take().onComplete();
+                }
+                return null;
+            }).toFuture();
 
-        Future<Object> accumulateFuture = EXECUTOR_EXTENSION.executor().submit(() -> {
-            accumulateAndTimerStarted.await();
-            int boundariesReceived = 0;
-            Iterator<Integer> itemsToPopulate = items.iterator();
-            while (itemsToPopulate.hasNext()) {
-                Accumulator<Integer, Iterable<Integer>> boundary = boundaries.take();
-                if (++boundariesReceived < maxBoundaries) {
-                    boundary.accumulate(itemsToPopulate.next());
-                } else {
-                    // add all items to the last boundary
-                    do {
-                        boundary.accumulate(itemsToPopulate.next());
-                    } while (itemsToPopulate.hasNext());
-                }
-                boundariesToFinish.add(boundary);
-            }
-            return null;
-        }).toFuture();
+            Future<Object> accumulateFuture = EXECUTOR_EXTENSION.executor().submit(() -> {
+                accumulateAndTimerStarted.await();
+                Iterator<Integer> itemsToPopulate = items.iterator();
+                while (itemsToPopulate.hasNext()) {
+                    Accumulator<Integer, Iterable<Integer>> boundary = boundaries.take();
+                    if (boundariesReceived.incrementAndGet() < maxBoundaries) {
+                        boundary.accumulate(itemsToPopulate.next());
+                    } else {
+                        // add all items to the last boundary
+                        do {
+                            boundary.accumulate(itemsToPopulate.next());
+                        } while (itemsToPopulate.hasNext());
+                    }
+                    boundariesToFinish.add(boundary);
+                }
+                return null;
+            }).toFuture();
 
-        boundariesDone.await();
-        timersFuture.get();
-        accumulateFuture.get();
-        Accumulator<Integer, Iterable<Integer>> boundary;
-        while ((boundary = boundariesToFinish.poll()) != null) {
-            for (Integer item : boundary.finish()) {
-                receivedFromBoundaries.add(item);
-            }
-        }
-        assertThat("Unexpected items received.", receivedFromBoundaries, contains(items.toArray()));
+            boundariesDone.await();
+            timersFuture.get();
+            accumulateFuture.get();
+            Accumulator<Integer, Iterable<Integer>> boundary;
+            while ((boundary = boundariesToFinish.poll()) != null) {
+                for (Integer item : boundary.finish()) {
+                    receivedFromBoundaries.add(item);
+                }
+            }
+            assertThat("Unexpected items received.", receivedFromBoundaries, contains(items.toArray()));
+        } catch (Throwable t) {
+            System.err.println("boundaries: " + boundaries.size());
+            System.err.println("boundariesToFinish: " + boundariesToFinish.size());
+            System.err.println("pending timers: " + timers.size());
+            System.err.println("boundariesReceived: " + boundariesReceived.get());
+            System.err.println("state: " + strategy.state());
+            t.printStackTrace();
+        }
     }
 
     @Test
Index: servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategy.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategy.java b/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategy.java
--- a/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategy.java	(revision d1d008ff9a19a8364e5114efcbcbf8edc79576f7)
+++ b/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategy.java	(date 1626150626546)
@@ -62,6 +62,10 @@
      */
     int bufferSizeHint();
 
+    default Object state() {
+        return null;
+    }
+
     /**
      * An intermediate mutable object that holds items till it is {@link #finish() finished}.
      * <p>
Index: servicetalk-concurrent-api/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/servicetalk-concurrent-api/build.gradle b/servicetalk-concurrent-api/build.gradle
--- a/servicetalk-concurrent-api/build.gradle	(revision d1d008ff9a19a8364e5114efcbcbf8edc79576f7)
+++ b/servicetalk-concurrent-api/build.gradle	(date 1626146528249)
@@ -45,3 +45,8 @@
 
   testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit5Version"
 }
+
+test {
+  outputs.upToDateWhen { false }
+  testLogging.showStandardStreams = true
+}
Index: servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategies.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategies.java b/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategies.java
--- a/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategies.java	(revision d1d008ff9a19a8364e5114efcbcbf8edc79576f7)
+++ b/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategies.java	(date 1626150626558)
@@ -137,10 +137,11 @@
         requireNonNull(accumulatorSupplier);
         requireNonNull(executor);
         return new BufferStrategy<T, Accumulator<T, B>, B>() {
+            private final State<T, B> state = new State<>();
             @Override
             public Publisher<Accumulator<T, B>> boundaries() {
                 return defer(() -> {
-                    State<T, B> state = new State<>();
+
                     CountingAccumulator<T, B> firstAccum =
                             new CountingAccumulator<>(state, accumulatorSupplier.get(), count);
                     state.beforeNewAccumulatorEmitted(firstAccum);
@@ -173,6 +174,11 @@
             public int bufferSizeHint() {
                 return count;
             }
+
+            @Override
+            public Object state() {
+                return state.state();
+            }
         };
     }
 
@@ -196,6 +202,10 @@
         @Nullable
         private volatile Object state;
 
+        Object state() {
+            return state;
+        }
+
         void countThresholdBreached(final Accumulator<T, B> breachedAccumulator) {
             for (;;) {
                 final Object cState = state;

```

**Comment by idelpivnitskiy** [comment]
This test was not flaky for more than a year. Reopen if it fails again
