### ISSUE TITLE
Flaky test: HttpTransportObserverTest.clientFailsRequestPayloadBody

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#1265]
https://ci.servicetalk.io/job/servicetalk-java11-prb/1829/testReport/junit/io.servicetalk.http.netty/HttpTransportObserverTest/clientFailsRequestPayloadBody_protocol_HTTP_2_/

```
io.servicetalk.http.netty.HttpTransportObserverTest.clientFailsRequestPayloadBody[protocol=HTTP_2]

Error Message
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.http.netty.HttpTransportObserverTest.clientFailsRequestPayloadBody(HttpTransportObserverTest.java:377)
But found this interaction on mock 'serverReadObserver':
-> at io.servicetalk.transport.api.CatchAllTransportObserver.safeReport(CatchAllTransportObserver.java:283)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.transport.api.CatchAllTransportObserver$CatchAllReadObserver.lambda$requestedToRead$0(CatchAllTransportObserver.java:203)
2. -> at io.servicetalk.transport.api.CatchAllTransportObserver.safeReport(CatchAllTransportObserver.java:283)
3. -> at io.servicetalk.transport.api.CatchAllTransportObserver$CatchAllReadObserver.lambda$requestedToRead$0(CatchAllTransportObserver.java:203)
4. -> at io.servicetalk.transport.api.CatchAllTransportObserver$CatchAllReadObserver.lambda$readFailed$1(CatchAllTransportObserver.java:213)
5. [?]-> at io.servicetalk.transport.api.CatchAllTransportObserver.safeReport(CatchAllTransportObserver.java:283)
Stacktrace
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.http.netty.HttpTransportObserverTest.clientFailsRequestPayloadBody(HttpTransportObserverTest.java:377)
But found this interaction on mock 'serverReadObserver':
-> at io.servicetalk.transport.api.CatchAllTransportObserver.safeReport(CatchAllTransportObserver.java:283)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.transport.api.CatchAllTransportObserver$CatchAllReadObserver.lambda$requestedToRead$0(CatchAllTransportObserver.java:203)
2. -> at io.servicetalk.transport.api.CatchAllTransportObserver.safeReport(CatchAllTransportObserver.java:283)
3. -> at io.servicetalk.transport.api.CatchAllTransportObserver$CatchAllReadObserver.lambda$requestedToRead$0(CatchAllTransportObserver.java:203)
4. -> at io.servicetalk.transport.api.CatchAllTransportObserver$CatchAllReadObserver.lambda$readFailed$1(CatchAllTransportObserver.java:213)
5. [?]-> at io.servicetalk.transport.api.CatchAllTransportObserver.safeReport(CatchAllTransportObserver.java:283)

	at io.servicetalk.http.netty.HttpTransportObserverTest.clientFailsRequestPayloadBody(HttpTransportObserverTest.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.mockito.internal.junit.JUnitRule$1.evaluateSafely(JUnitRule.java:57)
	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:48)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:171)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:163)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Standard Output
2020-12-10 03:13:30,346          server-executor-487-3 [ERROR] NettyHttpServer$NettyHttpServerConnection - Internal server error service=io.servicetalk.http.api.AsyncContextAwareHttpServiceFilter$1@73a8d99e connection=NettyHttpServerConnection([id: 0xa89e5cac, L:/127.0.0.1:42177 - R:/127.0.0.1:48750])
io.servicetalk.concurrent.internal.DeliberateException: Deliberate Exception
2020-12-10 03:13:31,317          server-executor-499-3 [ERROR] NettyHttpServer$NettyHttpServerConnection - Internal server error service=io.servicetalk.http.api.AsyncContextAwareHttpServiceFilter$1@71ab0230 connection=NettyHttpServerConnection([id: 0x97cfe702, L:/127.0.0.1:36653 - R:/127.0.0.1:46374](H2 - 3))
io.servicetalk.concurrent.internal.DeliberateException: Deliberate Exception
```

**Comment by idelpivnitskiy** [comment]
Fixed in #1702.
