### ISSUE TITLE
Flaky test: TaskBasedSignalOffloaderExecutorRejectionTests#singleOnErrorRejects

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#1305]
https://github.com/apple/servicetalk/pull/1300/checks?check_run_id=1665597451

```
Error: 1-01-07 23:05:18,092                    Test worker [ERROR] TaskBasedSignalOffloader       - Failed to execute task on the executor io.servicetalk.concurrent.api.internal.OffloaderAwareExecutor@387bcea5. Invoking Subscriber (onError()) in the caller thread. Subscriber ContextPreservingSingleSubscriberAndCancellable(io.servicetalk.concurrent.test.internal.TestSingleSubscriber@43c4c69f).
    java.util.concurrent.RejectedExecutionException: io.servicetalk.concurrent.internal.DeliberateException: Deliberate Exception
    	at io.servicetalk.concurrent.api.TaskBasedSignalOffloaderExecutorRejectionTests.lambda$new$0(TaskBasedSignalOffloaderExecutorRejectionTests.java:64) ~[test/:?]
    	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:39) ~[mockito-core-2.28.2.jar:?]
    	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:96) ~[mockito-core-2.28.2.jar:?]
    	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29) ~[mockito-core-2.28.2.jar:?]
    	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35) ~[mockito-core-2.28.2.jar:?]
    	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61) ~[mockito-core-2.28.2.jar:?]
    	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49) ~[mockito-core-2.28.2.jar:?]
    	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:126) ~[mockito-core-2.28.2.jar:?]
    	at io.servicetalk.concurrent.api.Executor$MockitoMock$1143728409.execute(Unknown Source) ~[servicetalk-concurrent-api-0.36.0-SNAPSHOT.jar:?]
    	at io.servicetalk.concurrent.api.internal.OffloaderAwareExecutor.execute(OffloaderAwareExecutor.java:53) ~[main/:?]
    	at io.servicetalk.concurrent.internal.TaskBasedSignalOffloader$AbstractOffloadedSingleValueSubscriber.terminal(TaskBasedSignalOffloader.java:535) ~[servicetalk-concurrent-internal-0.36.0-SNAPSHOT.jar:?]
    	at io.servicetalk.concurrent.internal.TaskBasedSignalOffloader$OffloadedSingleSubscriber.onError(TaskBasedSignalOffloader.java:586) ~[servicetalk-concurrent-internal-0.36.0-SNAPSHOT.jar:?]
    	at io.servicetalk.concurrent.api.ContextPreservingSingleSubscriber.onErrorSlowPath(ContextPreservingSingleSubscriber.java:115) ~[servicetalk-concurrent-api-0.36.0-SNAPSHOT.jar:?]
    	at io.servicetalk.concurrent.api.ContextPreservingSingleSubscriber.onError(ContextPreservingSingleSubscriber.java:107) ~[servicetalk-concurrent-api-0.36.0-SNAPSHOT.jar:?]
    	at io.servicetalk.concurrent.api.DelegatingSingleSubscriber.onError(DelegatingSingleSubscriber.java:43) ~[servicetalk-concurrent-api-0.36.0-SNAPSHOT-test-fixtures.jar:?]
    	at io.servicetalk.concurrent.api.DelegatingSingleSubscriber.onError(DelegatingSingleSubscriber.java:43) ~[servicetalk-concurrent-api-0.36.0-SNAPSHOT-test-fixtures.jar:?]
    	at io.servicetalk.concurrent.api.SequentialSingleSubscriberFunction$1.onError(SequentialSingleSubscriberFunction.java:56) ~[servicetalk-concurrent-api-0.36.0-SNAPSHOT-test-fixtures.jar:?]
    	at io.servicetalk.concurrent.api.TestSingle.onError(TestSingle.java:135) ~[servicetalk-concurrent-api-0.36.0-SNAPSHOT-test-fixtures.jar:?]
    	at io.servicetalk.concurrent.api.TaskBasedSignalOffloaderExecutorRejectionTests.lambda$singleOnErrorRejects$4(TaskBasedSignalOffloaderExecutorRejectionTests.java:130) ~[test/:?]
    	at io.servicetalk.concurrent.api.TaskBasedSignalOffloaderExecutorRejectionTests.singlePublishOnThrows(TaskBasedSignalOffloaderExecutorRejectionTests.java:215) [test/:?]
    	at io.servicetalk.concurrent.api.TaskBasedSignalOffloaderExecutorRejectionTests.singleOnErrorRejects(TaskBasedSignalOffloaderExecutorRejectionTests.java:130) [test/:?]
    	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.jar:4.13]
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.jar:4.13]
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.jar:4.13]
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.jar:4.13]
    	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.jar:4.13]
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.jar:4.13]
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.jar:4.13]
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.jar:4.13]
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110) [gradle-testing-jvm-6.7.1.jar:6.7.1]
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58) [gradle-testing-jvm-6.7.1.jar:6.7.1]
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38) [gradle-testing-jvm-6.7.1.jar:6.7.1]
    	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62) [gradle-testing-jvm-6.7.1.jar:6.7.1]
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51) [gradle-testing-base-6.7.1.jar:6.7.1]
    	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36) [gradle-messaging-6.7.1.jar:6.7.1]
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-6.7.1.jar:6.7.1]
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33) [gradle-messaging-6.7.1.jar:6.7.1]
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94) [gradle-messaging-6.7.1.jar:6.7.1]
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source) [?:?]
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119) [gradle-testing-base-6.7.1.jar:6.7.1]
    	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36) [gradle-messaging-6.7.1.jar:6.7.1]
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-6.7.1.jar:6.7.1]
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182) [gradle-messaging-6.7.1.jar:6.7.1]
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164) [gradle-messaging-6.7.1.jar:6.7.1]
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414) [gradle-messaging-6.7.1.jar:6.7.1]
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64) [gradle-base-services-6.7.1.jar:6.7.1]
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48) [gradle-base-services-6.7.1.jar:6.7.1]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56) [gradle-base-services-6.7.1.jar:6.7.1]
    	at java.lang.Thread.run(Thread.java:834) [?:?]
    Caused by: io.servicetalk.concurrent.internal.DeliberateException: Deliberate Exception

```

**Comment by idelpivnitskiy** [comment]
Nvm, it was a bug in the PR, fixed in https://github.com/apple/servicetalk/pull/1300/commits/baa8358deaa157a8a51fe1ddcf3d88b52a462d0f
