### ISSUE TITLE
SimpleHttpRequesterFilterTest *Connection* tests consistently fail on Ubuntu (20.04) Linux

### ISSUE THREAD

**Issue by chemicL** [apple/servicetalk#1536]
```
$ uname -srvpio
Linux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 GNU/Linux
```

The following fail:

```
SimpleHttpRequesterFilterTest > headersEnrichedByFilter[Connection-Secure] FAILED
    java.lang.AssertionError: 
    Expected: with toString() "127.0.1.2:28080"
         but: toString() was "127.0.1.2/<unresolved>:28080"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at io.servicetalk.http.api.SimpleHttpRequesterFilterTest.headersEnrichedByFilter(SimpleHttpRequesterFilterTest.java:129)

SimpleHttpRequesterFilterTest > headersEnrichedByFilter[Connection-Insecure] FAILED
    java.lang.AssertionError: 
    Expected: with toString() "127.0.1.2:28080"
         but: toString() was "127.0.1.2/<unresolved>:28080"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at io.servicetalk.http.api.SimpleHttpRequesterFilterTest.headersEnrichedByFilter(SimpleHttpRequesterFilterTest.java:129)

SimpleHttpRequesterFilterTest > headersEnrichedByFilter[ReservedConnection-Secure] FAILED
    java.lang.AssertionError: 
    Expected: with toString() "127.0.1.2:28080"
         but: toString() was "127.0.1.2/<unresolved>:28080"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at io.servicetalk.http.api.SimpleHttpRequesterFilterTest.headersEnrichedByFilter(SimpleHttpRequesterFilterTest.java:129)

SimpleHttpRequesterFilterTest > headersEnrichedByFilter[ReservedConnection-Insecure] FAILED
    java.lang.AssertionError: 
    Expected: with toString() "127.0.1.2:28080"
         but: toString() was "127.0.1.2/<unresolved>:28080"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at io.servicetalk.http.api.SimpleHttpRequesterFilterTest.headersEnrichedByFilter(SimpleHttpRequesterFilterTest.java:129)

867 tests completed, 4 failed, 82 skipped
```

**Comment by chemicL** [comment]
I think the important bit here is the JDK version, as I believe that combination causes the issue. With JDK8 I have not observed the problem.

```
$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

**Comment by idelpivnitskiy** [comment]
😕 they have changed impl of `InetSocketAddress#toSting()` in JDK14: https://github.com/openjdk/jdk/commit/f8440c33d22245ae02ec34982b8f1dd33ec7cc2b#diff-c2118fe850d1ddff33cf9f89d97ed854fca53c75627d6ae178e6660e20f7f4d6R108

**Comment by Scottmitch** [comment]
I think I fixed this when adding support for JDK 16 on CI 04b2fb4f7cbf453fac1cf4d4c39302d924f3ed5e.
