### ISSUE TITLE
ConnectionAcceptingNettyHttpServerTest test failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#1759]
https://github.com/apple/servicetalk/runs/3440129511

```
ConnectionAcceptingNettyHttpServerTest.testStopAcceptingAndResume()

java.util.concurrent.TimeoutException: Timed out waiting for the result
	at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:107)
	at io.servicetalk.concurrent.api.BlockingTestUtils.await(BlockingTestUtils.java:171)
	at io.servicetalk.http.netty.ConnectionAcceptingNettyHttpServerTest.assertConnectionRequestSucceeds(ConnectionAcceptingNettyHttpServerTest.java:126)
	at io.servicetalk.http.netty.ConnectionAcceptingNettyHttpServerTest.testStopAcceptingAndResume(ConnectionAcceptingNettyHttpServerTest.java:93)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/runs/3467797640

```
ConnectionAcceptingNettyHttpServerTest.testStopAcceptingAndResume()

java.util.concurrent.TimeoutException: Timed out waiting for the result
	at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:107)
	at io.servicetalk.concurrent.api.BlockingTestUtils.await(BlockingTestUtils.java:171)
	at io.servicetalk.http.netty.ConnectionAcceptingNettyHttpServerTest.assertConnectionRequestSucceeds(ConnectionAcceptingNettyHttpServerTest.java:126)
	at io.servicetalk.http.netty.ConnectionAcceptingNettyHttpServerTest.testStopAcceptingAndResume(ConnectionAcceptingNettyHttpServerTest.java:93)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/1776/checks?check_run_id=3478774871

```
ConnectionAcceptingNettyHttpServerTest > testStopAcceptingAndResume() FAILED

    java.util.concurrent.TimeoutException: Timed out waiting for the result
        at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:107)
        at io.servicetalk.concurrent.api.BlockingTestUtils.await(BlockingTestUtils.java:171)
        at io.servicetalk.http.netty.ConnectionAcceptingNettyHttpServerTest.assertConnectionRequestSucceeds(ConnectionAcceptingNettyHttpServerTest.java:126)
        at io.servicetalk.http.netty.ConnectionAcceptingNettyHttpServerTest.testStopAcceptingAndResume(ConnectionAcceptingNettyHttpServerTest.java:83)
```
