### ISSUE TITLE
Flaky test: HttpLifecycleObserverTest

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#1847]
https://github.com/apple/servicetalk/runs/3703697490 (0.41 branch)

```
HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpProtocol) [2] protocol=HTTP_2

org.mockito.exceptions.verification.VerificationInOrderFailure: 
Verification in order failure
Wanted but not invoked:
serverRequestObserver.onRequestError(
    <any java.io.IOException>
);
-> at io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpLifecycleObserverTest.java:281)
Wanted anywhere AFTER following interaction:
serverRequestObserver.onRequestData(
    NettyBuffer{buffer=UnreleasableNoZeroingHeapByteBuf(ridx: 0, widx: 7, cap: 7)}
);
-> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestData(BiHttpLifecycleObserver.java:133)

	at io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpLifecycleObserverTest.java:281)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by idelpivnitskiy** [comment]
Seeing this only for 0.41 branch:
https://github.com/apple/servicetalk/runs/3795514597

```
HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpProtocol) [2] protocol=HTTP_2
java.util.concurrent.TimeoutException: testClientCancelsRequestBeforeResponse(io.servicetalk.http.netty.HttpProtocol) timed out after 30 seconds

java.util.concurrent.TimeoutException: testClientCancelsRequestBeforeResponse(io.servicetalk.http.netty.HttpProtocol) timed out after 30 seconds
	at org.junit.jupiter.engine.extension.TimeoutInvocation.createTimeoutException(TimeoutInvocation.java:70)
	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:59)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpLifecycleObserverTest.java:263)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
		... 128 more
```

**Comment by Scottmitch** [comment]
0.46.2 release build failed on this https://github.com/apple/servicetalk/runs/5352635362

```
HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpProtocol) [2] protocol=HTTP_2

java.util.concurrent.TimeoutException: testClientCancelsRequestBeforeResponse(io.servicetalk.http.netty.HttpProtocol) timed out after 30 seconds

Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpLifecycleObserverTest.java:262)
```

**Comment by Scottmitch** [comment]
snapshot build failure https://github.com/apple/servicetalk/runs/6047222737

```
HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpProtocol) [2] protocol=HTTP_2

java.util.concurrent.TimeoutException: testClientCancelsRequestBeforeResponse(io.servicetalk.http.netty.HttpProtocol) timed out after 30 seconds

	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestBeforeResponse(HttpLifecycleObserverTest.java:262)

```

**Comment by bondolo** [comment]
https://github.com/apple/servicetalk/pull/2241/checks?check_run_id=6782660022

```
HttpLifecycleObserverTest.testClientCancelsRequestAfterResponse(HttpProtocol) [2] protocol=HTTP_2
Wanted but not invoked:
serverResponseObserver.onResponseDataRequested(
    <any long>
);
-> at io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestAfterResponse(HttpLifecycleObserverTest.java:345)

However, there was exactly 1 interaction with this mock:
serverResponseObserver.onResponseCancel();
-> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpResponseObserver.onResponseCancel(BiHttpLifecycleObserver.java:243)
```

**Comment by bondolo** [comment]
https://github.com/apple/servicetalk/pull/2242/checks?check_run_id=6784277876

```
HttpLifecycleObserverTest.testClientCancelsRequestAfterResponse(HttpProtocol) [2] protocol=HTTP_2
Wanted but not invoked:
serverResponseObserver.onResponseDataRequested(
    <any long>
);
-> at io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestAfterResponse(HttpLifecycleObserverTest.java:345)

However, there was exactly 1 interaction with this mock:
serverResponseObserver.onResponseCancel();
-> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpResponseObserver.onResponseCancel(BiHttpLifecycleObserver.java:243)
at app//io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestAfterResponse(HttpLifecycleObserverTest.java:345)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2262/checks?check_run_id=7251931050

```
HttpLifecycleObserverTest.testClientCancelsRequestAfterResponse(HttpProtocol) [2] protocol=HTTP_2
Wanted but not invoked:
serverResponseObserver.onResponseDataRequested(
    <any long>
);
-> at io.servicetalk.http.api.HttpLifecycleObserver$HttpResponseObserver.onResponseDataRequested(HttpLifecycleObserver.java:181)

However, there was exactly 1 interaction with this mock:
serverResponseObserver.onResponseCancel();
-> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpResponseObserver.onResponseCancel(BiHttpLifecycleObserver.java:243)
```
