### ISSUE TITLE
Flaky test: MalformedDataAfterHttpMessageTest

### ISSUE THREAD

**Issue by chemicL** [apple/servicetalk#1889]
https://github.com/apple/servicetalk/pull/1887/checks?check_run_id=3905793736

```
MalformedDataAfterHttpMessageTest > afterResponseNextClientRequestSucceeds() FAILED
java.lang.AssertionError: 
Expected: not <[id: 0x574fe329, L:/127.0.0.1:50732 ! R:127.0.0.1/127.0.0.1:39629]>
     but: was <[id: 0x574fe329, L:/127.0.0.1:50732 ! R:127.0.0.1/127.0.0.1:39629]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.http.netty.MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds(MalformedDataAfterHttpMessageTest.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/runs/3911534924

```
MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds()

java.lang.AssertionError: 
Expected: not <[id: 0x10564097, L:/127.0.0.1:40468 ! R:127.0.0.1/127.0.0.1:34849]>
     but: was <[id: 0x10564097, L:/127.0.0.1:40468 ! R:127.0.0.1/127.0.0.1:34849]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.http.netty.MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds(MalformedDataAfterHttpMessageTest.java:142)
	
```

**Comment by bondolo** [comment]
https://github.com/apple/servicetalk/pull/1832/checks?check_run_id=4029343881
```
MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds()
java.lang.AssertionError: 
Expected: not <[id: 0xe2da17cd, L:/127.0.0.1:44392 ! R:127.0.0.1/127.0.0.1:46877]>
     but: was <[id: 0xe2da17cd, L:/127.0.0.1:44392 ! R:127.0.0.1/127.0.0.1:46877]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.http.netty.MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds(MalformedDataAfterHttpMessageTest.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by bondolo** [comment]
https://github.com/apple/servicetalk/runs/4050035414?check_suite_focus=true

```
MalformedDataAfterHttpMessageTest > afterResponseNextClientRequestSucceeds() FAILED
    java.lang.AssertionError: 
    Expected: not <[id: 0x92be7d04, L:/127.0.0.1:53006 ! R:127.0.0.1/127.0.0.1:39999]>
         but: was <[id: 0x92be7d04, L:/127.0.0.1:53006 ! R:127.0.0.1/127.0.0.1:39999]>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.servicetalk.http.netty.MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds(MalformedDataAfterHttpMessageTest.java:142)
```

**Comment by bondolo** [comment]
https://github.com/apple/servicetalk/runs/4050129369?check_suite_focus=true
```
MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds()
java.lang.AssertionError: 
Expected: not <[id: 0x9de1e80d, L:/127.0.0.1:44648 ! R:127.0.0.1/127.0.0.1:37659]>
     but: was <[id: 0x9de1e80d, L:/127.0.0.1:44648 ! R:127.0.0.1/127.0.0.1:37659]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.http.netty.MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds(MalformedDataAfterHttpMessageTest.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by bondolo** [comment]
https://github.com/apple/servicetalk/runs/4050129369?check_suite_focus=true

```
MalformedDataAfterHttpMessageTest > afterResponseNextClientRequestSucceeds() FAILED
    java.lang.AssertionError: 
    Expected: not <[id: 0x9de1e80d, L:/127.0.0.1:44648 ! R:127.0.0.1/127.0.0.1:37659]>
         but: was <[id: 0x9de1e80d, L:/127.0.0.1:44648 ! R:127.0.0.1/127.0.0.1:37659]>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.servicetalk.http.netty.MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds(MalformedDataAfterHttpMessageTest.java:142)
```

**Comment by bondolo** [comment]
https://github.com/apple/servicetalk/pull/1832/checks?check_run_id=4050770988
```
MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds()
java.lang.AssertionError: 
Expected: not <[id: 0x57e7d4d9, L:/127.0.0.1:37492 ! R:127.0.0.1/127.0.0.1:35831]>
     but: was <[id: 0x57e7d4d9, L:/127.0.0.1:37492 ! R:127.0.0.1/127.0.0.1:35831]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.http.netty.MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds(MalformedDataAfterHttpMessageTest.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/1924/checks?check_run_id=4051906973

```
MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds()
java.lang.AssertionError: 
Expected: not <[id: 0xde698240, L:/127.0.0.1:49354 ! R:127.0.0.1/127.0.0.1:36569]>
     but: was <[id: 0xde698240, L:/127.0.0.1:49354 ! R:127.0.0.1/127.0.0.1:36569]>
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/runs/4052225075

```
java.lang.AssertionError: 
Expected: not <[id: 0xdf133fbd, L:/127.0.0.1:41826 ! R:127.0.0.1/127.0.0.1:39117]>
     but: was <[id: 0xdf133fbd, L:/127.0.0.1:41826 ! R:127.0.0.1/127.0.0.1:39117]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.http.netty.MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds(MalformedDataAfterHttpMessageTest.java:142)
	
```
