### ISSUE TITLE
ProtocolCompatibilityTest.serviceTalkToGrpcJavaClientTimeout test failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#1891]
https://github.com/apple/servicetalk/pull/1890/checks?check_run_id=3907388136

```
ProtocolCompatibilityTest.[10] true, true, gzip

org.opentest4j.AssertionFailedError: grpcStatus: GrpcStatus{code=UNKNOWN, cause=java.util.concurrent.TimeoutException: timeout after 100ms, description='null'} ==> expected: <DEADLINE_EXCEEDED> but was: <UNKNOWN>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1152)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.assertGrpcStatusException(ProtocolCompatibilityTest.java:951)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.validateGrpcErrorInResponse(ProtocolCompatibilityTest.java:936)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.testGrpcErrorStreaming(ProtocolCompatibilityTest.java:896)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.testGrpcError(ProtocolCompatibilityTest.java:874)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.serviceTalkToGrpcJavaClientTimeout(ProtocolCompatibilityTest.java:616)
	
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/runs/5473545989

```
org.opentest4j.AssertionFailedError: grpcStatus: GrpcStatus{code=UNKNOWN, cause=java.util.concurrent.TimeoutException: timeout after 100ms, description='null'} ==> expected: <DEADLINE_EXCEEDED> but was: <UNKNOWN>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1152)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.assertGrpcStatusException(ProtocolCompatibilityTest.java:906)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.validateGrpcErrorInResponse(ProtocolCompatibilityTest.java:891)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.testGrpcErrorScalar(ProtocolCompatibilityTest.java:870)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.testGrpcError(ProtocolCompatibilityTest.java:831)
	at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.serviceTalkToGrpcJavaClientTimeout(ProtocolCompatibilityTest.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by bondolo** [comment]
https://github.com/apple/servicetalk/actions/runs/1999747812
```
ProtocolCompatibilityTest > serviceTalkToGrpcJavaClientTimeout(boolean, boolean, String) > io.servicetalk.grpc.netty.ProtocolCompatibilityTest.serviceTalkToGrpcJavaClientTimeout(boolean, boolean, String)[12] FAILED
    org.opentest4j.AssertionFailedError: grpcStatus: GrpcStatus{code=UNKNOWN, cause=java.util.concurrent.TimeoutException: timeout after 100ms, description='null'} ==> expected: <DEADLINE_EXCEEDED> but was: <UNKNOWN>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1152)
        at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.assertGrpcStatusException(ProtocolCompatibilityTest.java:906)
        at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.validateGrpcErrorInResponse(ProtocolCompatibilityTest.java:891)
        at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.testGrpcErrorStreaming(ProtocolCompatibilityTest.java:851)
        at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.testGrpcError(ProtocolCompatibilityTest.java:829)
        at io.servicetalk.grpc.netty.ProtocolCompatibilityTest.serviceTalkToGrpcJavaClientTimeout(ProtocolCompatibilityTest.java:571)
```

**Comment by idelpivnitskiy** [comment]
This was not flaky for more than a year. Reopen if it happens again.
