### ISSUE TITLE
MultiAddressUrlHttpClientTest test failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2008]
local macOS build, JDK 17.0.1

```
requestWithAbsoluteFormRequestTargetWithInvalidHost()

java.lang.AssertionError: 
Expected: is an instance of java.net.UnknownHostException
     but: <io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: invalid./172.19.52.2:63502> is a io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.http.netty.MultiAddressUrlHttpClientTest.requestWithInvalidHost(MultiAddressUrlHttpClientTest.java:222)
	at io.servicetalk.http.netty.MultiAddressUrlHttpClientTest.requestWithAbsoluteFormRequestTargetWithInvalidHost(MultiAddressUrlHttpClientTest.java:213)
	

```

**Comment by idelpivnitskiy** [comment]
This was not flaky for more than a year. Reopen if it happens again.
