### ISSUE TITLE
GrpcLifecycleObserverTest

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2298]
```
GrpcLifecycleObserverTest.testBiDiStream(boolean) [2] error=true

org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
But found this interaction on mock 'clientRequestObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestData(BiGrpcLifecycleObserver.java:143)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestComplete(BiGrpcLifecycleObserver.java:161)
4. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)

	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.runTest(GrpcLifecycleObserverTest.java:219)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.testBiDiStream(GrpcLifecycleObserverTest.java:205)
	
```

**Comment by tkountis** [comment]
```
GrpcLifecycleObserverTest.testBiDiStream(boolean) [1] error=false

org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
But found this interaction on mock 'clientRequestObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestData(BiGrpcLifecycleObserver.java:143)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestComplete(BiGrpcLifecycleObserver.java:161)
4. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/runs/8172098957

```
GrpcLifecycleObserverTest.testResponseStream(boolean) [1] error=false

org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
But found this interaction on mock 'serverResponseObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseData(BiGrpcLifecycleObserver.java:208)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseTrailers(BiGrpcLifecycleObserver.java:217)
4. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onGrpcStatus(BiGrpcLifecycleObserver.java:226)
5. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseComplete(BiGrpcLifecycleObserver.java:235)
6. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)

	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.runTest(GrpcLifecycleObserverTest.java:221)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.testResponseStream(GrpcLifecycleObserverTest.java:199)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2344/checks?check_run_id=8259323439

```
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
But found this interaction on mock 'serverResponseObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseData(BiGrpcLifecycleObserver.java:208)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseTrailers(BiGrpcLifecycleObserver.java:217)
4. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onGrpcStatus(BiGrpcLifecycleObserver.java:226)
5. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseComplete(BiGrpcLifecycleObserver.java:235)
6. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/runs/8280598657

```
GrpcLifecycleObserverTest.testResponseStream(boolean) [1] error=false

org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
But found this interaction on mock 'serverResponseObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseData(BiGrpcLifecycleObserver.java:208)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseTrailers(BiGrpcLifecycleObserver.java:217)
4. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onGrpcStatus(BiGrpcLifecycleObserver.java:226)
5. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseComplete(BiGrpcLifecycleObserver.java:235)
6. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)

	at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
	at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.runTest(GrpcLifecycleObserverTest.java:221)
	at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.testResponseStream(GrpcLifecycleObserverTest.java:199)
	
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2357/checks?check_run_id=8307899394

GrpcLifecycleObserverTest.testBiDiStream(boolean) [2] error=true
```
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
But found this interaction on mock 'clientRequestObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestData(BiGrpcLifecycleObserver.java:143)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestComplete(BiGrpcLifecycleObserver.java:161)
4. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)

	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.runTest(GrpcLifecycleObserverTest.java:219)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.testBiDiStream(GrpcLifecycleObserverTest.java:205)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2361/checks?check_run_id=8312690839

```
GrpcLifecycleObserverTest.testResponseStream(boolean) [1] error=false
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
But found this interaction on mock 'serverResponseObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseData(BiGrpcLifecycleObserver.java:208)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseTrailers(BiGrpcLifecycleObserver.java:217)
4. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onGrpcStatus(BiGrpcLifecycleObserver.java:226)
5. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseComplete(BiGrpcLifecycleObserver.java:235)
6. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.runTest(GrpcLifecycleObserverTest.java:221)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.testResponseStream(GrpcLifecycleObserverTest.java:199)
	at java.base@11.0.16/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2375/checks?check_run_id=8605151664

```
GrpcLifecycleObserverTest.testResponseStream(boolean) [1] error=false
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
But found this interaction on mock 'serverResponseObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseData(BiGrpcLifecycleObserver.java:208)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseTrailers(BiGrpcLifecycleObserver.java:217)
4. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onGrpcStatus(BiGrpcLifecycleObserver.java:226)
5. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseComplete(BiGrpcLifecycleObserver.java:235)
6. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)

	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:271)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.runTest(GrpcLifecycleObserverTest.java:221)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.testResponseStream(GrpcLifecycleObserverTest.java:199)
	at java.base@11.0.16/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
