### ISSUE TITLE
Publisher OffloadingTest

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2325]
local build, openjdk 11.0.15.10, macOS m1

```
OffloadingTest > testOffloading(OffloadCase) > io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadCase)[13] FAILED

java.lang.AssertionError: Executor was not initialized
	at io.servicetalk.concurrent.api.ExecutorExtension.executor(ExecutorExtension.java:108)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)
```

**Comment by Scottmitch** [comment]
local build, openjdk 17.0.3, macOS m1

```
[10] PUBLISH_ON_CONDITIONAL_NEVER

java.lang.AssertionError: Executor was not initialized
	at io.servicetalk.concurrent.api.ExecutorExtension.executor(ExecutorExtension.java:108)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)

[12] PUBLISH_ON_ERROR

java.lang.AssertionError: Executor was not initialized
	at io.servicetalk.concurrent.api.ExecutorExtension.executor(ExecutorExtension.java:108)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)

[9] PUBLISH_ON_SUCCESS

java.lang.AssertionError: Executor was not initialized
	at io.servicetalk.concurrent.api.ExecutorExtension.executor(ExecutorExtension.java:108)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)
```

**Comment by Scottmitch** [comment]
local build

```
OffloadingTest [7] SUBSCRIBE_ON_ERROR

java.lang.AssertionError: Executor was not initialized
	at io.servicetalk.concurrent.api.ExecutorExtension.executor(ExecutorExtension.java:108)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)

```

**Comment by Scottmitch** [comment]
local build jdk 17

```
[10] PUBLISH_ON_CONDITIONAL_NEVER

java.lang.AssertionError: Executor was not initialized
	at io.servicetalk.concurrent.api.ExecutorExtension.executor(ExecutorExtension.java:108)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)

[9] PUBLISH_ON_SUCCESS
java.lang.AssertionError: Executor was not initialized
	at io.servicetalk.concurrent.api.ExecutorExtension.executor(ExecutorExtension.java:108)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)
	
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2397/checks?check_run_id=8947806037

```
OffloadingTest.[13] PUBLISH_ON_CANCEL

java.lang.AssertionError: Executor was not initialized
	at io.servicetalk.concurrent.api.ExecutorExtension.executor(ExecutorExtension.java:108)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)


```

**Comment by 82baras** [comment]
A full dump of the message I saw on my intel mac:

```jaa

> Task :servicetalk-concurrent-api-internal:test

OffloadingTest > testOffloading(OffloadCase) > [12] PUBLISH_ON_ERROR FAILED
    java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@8c521fd[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7da67d0[Wrapped task = io.servicetalk.concurrent.api.ContextPreservingRunnable@ce6b5ab]] rejected from java.util.concurrent.ThreadPoolExecutor@1a4e4406[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at io.servicetalk.concurrent.api.DefaultExecutor$1.apply(DefaultExecutor.java:192)
        at io.servicetalk.concurrent.api.DefaultExecutor$1.apply(DefaultExecutor.java:176)
        at io.servicetalk.concurrent.api.DefaultExecutor.execute(DefaultExecutor.java:119)
        at io.servicetalk.concurrent.api.ContextPreservingStExecutor.execute(ContextPreservingStExecutor.java:39)
        at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
        at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)

133 tests completed, 1 failed
```

**Comment by Scottmitch** [comment]
m1 MacBook local build:

```
java -version
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (Zulu 8.64.0.15-CA-macos-aarch64) (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM (Zulu 8.64.0.15-CA-macos-aarch64) (build 25.342-b07, mixed mode)
```

```
OffloadingTest > testOffloading(OffloadCase) > [13] PUBLISH_ON_CANCEL FAILED
    java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6a49fd3c rejected from java.util.concurrent.ThreadPoolExecutor@3c72600e[Terminated, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at io.servicetalk.concurrent.api.DefaultExecutor$1.apply(DefaultExecutor.java:192)
        at io.servicetalk.concurrent.api.DefaultExecutor$1.apply(DefaultExecutor.java:176)
        at io.servicetalk.concurrent.api.DefaultExecutor.execute(DefaultExecutor.java:119)
        at io.servicetalk.concurrent.api.ContextPreservingStExecutor.execute(ContextPreservingStExecutor.java:39)
        at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
        at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2744/checks?check_run_id=18464314134

```
OffloadingTest.[9] PUBLISH_ON_SUCCESS

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2927b65c rejected from java.util.concurrent.ThreadPoolExecutor@379f8fa[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.servicetalk.concurrent.api.DefaultExecutor$1.apply(DefaultExecutor.java:192)
	at io.servicetalk.concurrent.api.DefaultExecutor$1.apply(DefaultExecutor.java:176)
	at io.servicetalk.concurrent.api.DefaultExecutor.execute(DefaultExecutor.java:119)
	at io.servicetalk.concurrent.api.ContextPreservingStExecutor.execute(ContextPreservingStExecutor.java:39)
	at io.servicetalk.concurrent.api.publisher.AbstractPublisherOffloadingTest.testOffloading(AbstractPublisherOffloadingTest.java:184)
	at io.servicetalk.concurrent.api.publisher.OffloadingTest.testOffloading(OffloadingTest.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
