### ISSUE TITLE
HttpLifecycleObserverTest failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2343]
https://github.com/apple/servicetalk/pull/2341/checks?check_run_id=8172351623

```
HttpLifecycleObserverTest.testCompleteWithPayloadBodyAndTrailers(HttpProtocol) [2] protocol=HTTP_2

org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.http.netty.HttpLifecycleObserverTest.verifyObservers(HttpLifecycleObserverTest.java:395)
But found this interaction on mock 'serverRequestObserver':
-> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestDataRequested(BiHttpLifecycleObserver.java:133)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestDataRequested(BiHttpLifecycleObserver.java:133)
2. -> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestData(BiHttpLifecycleObserver.java:142)
3. -> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestComplete(BiHttpLifecycleObserver.java:160)
4. [?]-> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestDataRequested(BiHttpLifecycleObserver.java:133)

	at app//io.servicetalk.http.netty.HttpLifecycleObserverTest.verifyObservers(HttpLifecycleObserverTest.java:395)
	at app//io.servicetalk.http.netty.HttpLifecycleObserverTest.testCompleteWithPayloadBodyAndTrailers(HttpLifecycleObserverTest.java:168)
```

related? https://github.com/apple/servicetalk/issues/1847

**Comment by Scottmitch** [comment]
timeout during local build, maybe we need to increase timeouts too?

```
HttpLifecycleObserverTest#testClientCancelsRequestAfterResponse(HttpProtocol) [1] protocol=HTTP_1

java.util.concurrent.TimeoutException: testClientCancelsRequestAfterResponse(io.servicetalk.http.netty.HttpProtocol) timed out after 10 seconds
	at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
	at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:58)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)


	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.http.netty.HttpLifecycleObserverTest.testClientCancelsRequestAfterResponse(HttpLifecycleObserverTest.java:328)
```
