### ISSUE TITLE
Flaky H2PriorKnowledgeFeatureParityTest.serverGracefulClose

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#2378]
Unfortunately, #2375 didn't fix the issue. Saw a new test failure:

https://github.com/apple/servicetalk/runs/8607775207

```
H2PriorKnowledgeFeatureParityTest.serverGracefulClose(HttpTestExecutionStrategy, boolean) [1] client=NO_OFFLOAD, h2PriorKnowledge=true
java.util.concurrent.TimeoutException: serverGracefulClose(io.servicetalk.http.netty.HttpTestExecutionStrategy, boolean) timed out after 30 seconds
...
	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.serverGracefulClose(H2PriorKnowledgeFeatureParityTest.java:1200)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		...
```

**Comment by Scottmitch** [comment]
```
H2PriorKnowledgeFeatureParityTest.serverGracefulClose(HttpTestExecutionStrategy, boolean) [1] client=NO_OFFLOAD, h2PriorKnowledge=true
java.util.concurrent.TimeoutException: serverGracefulClose(io.servicetalk.http.netty.HttpTestExecutionStrategy, boolean) timed out after 30 seconds

	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
		at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.serverGracefulClose(H2PriorKnowledgeFeatureParityTest.java:1200)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/runs/8648726776

```
H2PriorKnowledgeFeatureParityTest.serverGracefulClose(HttpTestExecutionStrategy, boolean) [1] client=NO_OFFLOAD, h2PriorKnowledge=true
java.util.concurrent.TimeoutException: serverGracefulClose(io.servicetalk.http.netty.HttpTestExecutionStrategy, boolean) timed out after 30 seconds
...
	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.serverGracefulClose(H2PriorKnowledgeFeatureParityTest.java:1200)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/runs/8974087179

```
H2PriorKnowledgeFeatureParityTest.serverGracefulClose(HttpTestExecutionStrategy, boolean) [3] client=DEFAULT, h2PriorKnowledge=true
java.util.concurrent.TimeoutException: serverGracefulClose(io.servicetalk.http.netty.HttpTestExecutionStrategy, boolean) timed out after 30 seconds

	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.serverGracefulClose(H2PriorKnowledgeFeatureParityTest.java:1267)
		
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2416/checks?check_run_id=9401315527

```
H2PriorKnowledgeFeatureParityTest.serverGracefulClose(HttpTestExecutionStrategy, boolean) [3] client=DEFAULT, h2PriorKnowledge=true

Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.serverGracefulClose(H2PriorKnowledgeFeatureParityTest.java:1341)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2424/checks?check_run_id=9505593566

```
H2PriorKnowledgeFeatureParityTest.serverGracefulClose(HttpTestExecutionStrategy, boolean) [3] client=DEFAULT, h2PriorKnowledge=true
java.util.concurrent.TimeoutException: serverGracefulClose(io.servicetalk.http.netty.HttpTestExecutionStrategy, boolean) timed out after 30 seconds

	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.serverGracefulClose(H2PriorKnowledgeFeatureParityTest.java:1341)
		
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2442/checks?check_run_id=9677302588

```
H2PriorKnowledgeFeatureParityTest.serverGracefulClose(HttpTestExecutionStrategy, boolean) [3] client=DEFAULT, h2PriorKnowledge=true

java.util.concurrent.TimeoutException: serverGracefulClose(io.servicetalk.http.netty.HttpTestExecutionStrategy, boolean) timed out after 30 seconds

	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
		at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.serverGracefulClose(H2PriorKnowledgeFeatureParityTest.java:1341)

```

**Comment by Scottmitch** [comment]
I'm not 100% sure that #2444 resolves this issue as I'm not able to reproduce locally but seems likely given the symptoms. If not lets re-open or open a new issue.
