### ISSUE TITLE
SslAndNonSslConnectionsTest

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2403]
https://github.com/apple/servicetalk/actions/runs/3278125767/jobs/5396262303

```
SslAndNonSslConnectionsTest.nonSecureClientToSecureServerClosesConnection()

org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <java.nio.channels.ClosedChannelException> but was: <io.netty.channel.unix.Errors.NativeIoException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at io.servicetalk.http.netty.SslAndNonSslConnectionsTest.nonSecureClientToSecureServerClosesConnection(SslAndNonSslConnectionsTest.java:140)

Caused by: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```

**Comment by bryce-anderson** [comment]
https://github.com/apple/servicetalk/actions/runs/6854324050/job/18636992446?pr=2754
```
SslAndNonSslConnectionsTest > nonSecureClientToSecureServerClosesConnection() FAILED
    org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <java.nio.channels.ClosedChannelException> but was: <io.netty.channel.unix.Errors.NativeIoException>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3083)
        at io.servicetalk.http.netty.SslAndNonSslConnectionsTest.nonSecureClientToSecureServerClosesConnection(SslAndNonSslConnectionsTest.java:140)

        Caused by:
        io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```

**Comment by bryce-anderson** [comment]
The unexpected exception surfaces here: https://github.com/apple/servicetalk/blob/main/servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java#L888
The channel is attempting to read and finds the socket closed. This ends up being propagated as a `IoException` via the channel `exceptionCaught` pathway and doesn't get filtered out anywhere.
