### ISSUE TITLE
RetryingHttpRequesterFilterTest

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2405]
https://github.com/apple/servicetalk/runs/8974087179

```
RetryingHttpRequesterFilterTest.testResponseMapper()

java.lang.AssertionError: Response payload body was not drained on every mapping
Expected: is <4>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.servicetalk.http.netty.RetryingHttpRequesterFilterTest.testResponseMapper(RetryingHttpRequesterFilterTest.java:198)

```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/actions/runs/3374519684

```
RetryingHttpRequesterFilterTest > testResponseMapper() FAILED
    java.lang.AssertionError: Response payload body was not drained on every mapping
    Expected: is <4>
         but: was <3>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at io.servicetalk.http.netty.RetryingHttpRequesterFilterTest.testResponseMapper(RetryingHttpRequesterFilterTest.java:198)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/runs/9451704414

```
RetryingHttpRequesterFilterTest.testResponseMapper()
java.lang.AssertionError: Response payload body was not drained on every mapping
Expected: is <4>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.servicetalk.http.netty.RetryingHttpRequesterFilterTest.testResponseMapper(RetryingHttpRequesterFilterTest.java:198)
	...
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/runs/9508972057

```
RetryingHttpRequesterFilterTest.testResponseMapper()
java.lang.AssertionError: Response payload body was not drained on every mapping
Expected: is <4>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.servicetalk.http.netty.RetryingHttpRequesterFilterTest.testResponseMapper(RetryingHttpRequesterFilterTest.java:198)
	
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2419/checks?check_run_id=9582382758
```
RetryingHttpRequesterFilterTest.testResponseMapper()
java.lang.AssertionError: Response payload body was not drained on every mapping
Expected: is <4>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.servicetalk.http.netty.RetryingHttpRequesterFilterTest.testResponseMapper(RetryingHttpRequesterFilterTest.java:198)
```
