### ISSUE TITLE
GrpcLifecycleObserverTest

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2414]
https://github.com/apple/servicetalk/runs/9343043456

```
GrpcLifecycleObserverTest.testBiDiStream(boolean) [1] error=false
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:276)
But found this interaction on mock 'clientRequestObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestData(BiGrpcLifecycleObserver.java:143)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestComplete(BiGrpcLifecycleObserver.java:161)
4. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)


at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:276)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.runTest(GrpcLifecycleObserverTest.java:224)
	at app//io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.testBiDiStream(GrpcLifecycleObserverTest.java:207)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2461/checks?check_run_id=10003887147

```
GrpcLifecycleObserverTest.testBiDiStream(boolean) [1] error=false
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:276)
But found this interaction on mock 'clientRequestObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestData(BiGrpcLifecycleObserver.java:143)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestComplete(BiGrpcLifecycleObserver.java:161)
4. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcRequestObserver.onRequestDataRequested(BiGrpcLifecycleObserver.java:134)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2693/checks?check_run_id=16800089358

```
GrpcLifecycleObserverTest.testResponseStream(boolean) [1] error=false

org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:276)
But found this interaction on mock 'serverResponseObserver':
-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)
2. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseData(BiGrpcLifecycleObserver.java:208)
3. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseTrailers(BiGrpcLifecycleObserver.java:217)
4. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onGrpcStatus(BiGrpcLifecycleObserver.java:226)
5. -> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseComplete(BiGrpcLifecycleObserver.java:235)
6. [?]-> at io.servicetalk.grpc.utils.BiGrpcLifecycleObserver$BiGrpcResponseObserver.onResponseDataRequested(BiGrpcLifecycleObserver.java:199)

	at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.verifyObservers(GrpcLifecycleObserverTest.java:276)
	at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.runTest(GrpcLifecycleObserverTest.java:226)
	at io.servicetalk.grpc.netty.GrpcLifecycleObserverTest.testResponseStream(GrpcLifecycleObserverTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by idelpivnitskiy** [comment]
Haven't seen this fail for a long time. Reopen if it happens again
