### ISSUE TITLE
HttpLifecycleObserverTest.testCompleteEmptyMessageBody

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2439]
https://github.com/apple/servicetalk/pull/2438/checks?check_run_id=9674873644
```
HttpLifecycleObserverTest.testCompleteEmptyMessageBody(HttpProtocol) [2] protocol=HTTP_2
org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at io.servicetalk.http.netty.HttpLifecycleObserverTest.verifyObservers(HttpLifecycleObserverTest.java:398)
But found this interaction on mock 'serverRequestObserver':
-> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestDataRequested(BiHttpLifecycleObserver.java:133)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestComplete(BiHttpLifecycleObserver.java:160)
2. [?]-> at io.servicetalk.http.utils.BiHttpLifecycleObserver$BiHttpRequestObserver.onRequestDataRequested(BiHttpLifecycleObserver.java:133)

at app//io.servicetalk.http.netty.HttpLifecycleObserverTest.verifyObservers(HttpLifecycleObserverTest.java:398)
at app//io.servicetalk.http.netty.HttpLifecycleObserverTest.testCompleteEmptyMessageBody(HttpLifecycleObserverTest.java:155)
```

**Comment by Scottmitch** [comment]
Unable to repro locally. I will try to update mockito (https://github.com/apple/servicetalk/pull/2440) just in case, but assume the issue is on our side.

**Comment by idelpivnitskiy** [comment]
This test was not flaky for almost a year and I did some improvements in this area. Will close this issue. If it happens again, please reopen.
