### ISSUE TITLE
CacheConnectionHttpLoadBalanceFactoryTest

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#2485]
https://github.com/apple/servicetalk/runs/10560802924
```
CacheConnectionHttpLoadBalanceFactoryTest.h1OrH2(int, int, boolean, boolean) [9] numRequests=1000 maxConcurrency=100 clientH2=true serverH2=true

java.util.concurrent.TimeoutException: h1OrH2(int, int, boolean, boolean) timed out after 30 seconds
...
	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:91)
		at io.servicetalk.http.netty.CacheConnectionHttpLoadBalanceFactoryTest.h1OrH2(CacheConnectionHttpLoadBalanceFactoryTest.java:116)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2529/checks?check_run_id=11665238657
```
CacheConnectionHttpLoadBalanceFactoryTest.h1OrH2(int, int, boolean, boolean) [8] numRequests=201 maxConcurrency=100 clientH2=true serverH2=true

java.util.concurrent.TimeoutException: h1OrH2(int, int, boolean, boolean) timed out after 30 seconds
...
	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:91)
		at io.servicetalk.http.netty.CacheConnectionHttpLoadBalanceFactoryTest.h1OrH2(CacheConnectionHttpLoadBalanceFactoryTest.java:116)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Scottmitch** [comment]
```
CacheConnectionHttpLoadBalanceFactoryTest.h1OrH2(int, int, boolean, boolean) [9] numRequests=1000 maxConcurrency=100 clientH2=true serverH2=true

java.util.concurrent.TimeoutException: h1OrH2(int, int, boolean, boolean) timed out after 30 seconds

	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.http.netty.CacheConnectionHttpLoadBalanceFactoryTest.h1OrH2(CacheConnectionHttpLoadBalanceFactoryTest.java:116)

```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2746/checks?check_run_id=18541669002

```
CacheConnectionHttpLoadBalanceFactoryTest.h1OrH2(int, int, boolean, boolean) [9] numRequests=1000 maxConcurrency=100 clientH2=true serverH2=true

java.util.concurrent.TimeoutException: h1OrH2(int, int, boolean, boolean) timed out after 30 seconds
...
	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.http.netty.CacheConnectionHttpLoadBalanceFactoryTest.h1OrH2(CacheConnectionHttpLoadBalanceFactoryTest.java:116)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

**Comment by bryce-anderson** [comment]
I've tried to repro this with a few different settings and adding some extra work to hopefully induce some context switches but haven't had any success. See https://github.com/apple/servicetalk/pull/2760 for details.

**Comment by idelpivnitskiy** [comment]
Haven't seen this fail for a long time. Reopen if it happens again
