### ISSUE TITLE
IoUringTest.ioUringIsAvailableOnLinux()

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2585]
https://github.com/apple/servicetalk/pull/2584/checks?check_run_id=13318053938

Possible duplicate: https://github.com/apple/servicetalk/issues/2265

```
Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:91)
		at io.servicetalk.http.netty.IoUringTest.ioUringIsAvailableOnLinux(IoUringTest.java:96)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2646/checks?check_run_id=14929019291

```
	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.http.netty.IoUringTest.ioUringIsAvailableOnLinux(IoUringTest.java:95)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
		at java.base/java.lang.reflect.Method.invoke(Method.java:578)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)
		... 105 more
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2688/checks?check_run_id=16492447366

```
Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.http.netty.IoUringTest.ioUringIsAvailableOnLinux(IoUringTest.java:95)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
		at java.base/java.lang.reflect.Method.invoke(Method.java:578)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2684/checks?check_run_id=17275743063
```
IoUringTest.ioUringIsAvailableOnLinux(boolean) [1] noOffloading=false

java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds

	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.http.netty.IoUringTest.ioUringIsAvailableOnLinux(IoUringTest.java:95)
```

**Comment by idelpivnitskiy** [comment]
```
IoUringTest.ioUringIsAvailableOnLinux(boolean) [1] noOffloading=false

java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
...
	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.http.netty.IoUringTest.ioUringIsAvailableOnLinux(IoUringTest.java:95)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by bryce-anderson** [comment]
https://github.com/apple/servicetalk/actions/runs/6871425148/job/18688226181?pr=2760
```
IoUringTest > ioUringIsAvailableOnLinux(boolean) > ioUringIsAvailableOnLinux(boolean) [2] noOffloading=true FAILED
    java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
    ...
```
There wasn't an attached suppressed exception.

**Comment by bryce-anderson** [comment]
It turns out this is a netty bug that affects short lived loops. https://github.com/netty/netty-incubator-transport-io_uring/pull/227

**Comment by idelpivnitskiy** [comment]
Happened again:
https://github.com/apple/servicetalk/pull/2777/checks?check_run_id=19459240771

```
java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
...
	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.http.netty.IoUringTest.ioUringIsAvailableOnLinux(IoUringTest.java:95)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)
		... 105 more
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/pull/2832/checks?check_run_id=21461628619
```
IoUringTest.ioUringIsAvailableOnLinux(boolean) [1] noOffloading=false
java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
	at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
...
	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.http.netty.IoUringTest.ioUringIsAvailableOnLinux(IoUringTest.java:95)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)
		... 105 more
```

**Comment by bryce-anderson** [comment]
https://github.com/apple/servicetalk/actions/runs/11109873437/job/30866255479?pr=3070#step:8:1483
```
IoUringTest > ioUringIsAvailableOnLinux(boolean) > ioUringIsAvailableOnLinux(boolean) [2] noOffloading=true FAILED
    java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
        at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:58)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
```

**Comment by bryce-anderson** [comment]
https://github.com/apple/servicetalk/actions/runs/11339965186/job/31535582403#step:8:2130
```
IoUringTest > ioUringIsAvailableOnLinux(boolean) > ioUringIsAvailableOnLinux(boolean) [1] noOffloading=false FAILED
    java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
        at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:58)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/actions/runs/11850122700/job/33024501131#step:8:1487

```
IoUringTest > ioUringIsAvailableOnLinux(boolean) > ioUringIsAvailableOnLinux(boolean) [1] noOffloading=false FAILED
    java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
        at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:58)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
       
```

**Comment by bryce-anderson** [comment]
https://github.com/apple/servicetalk/actions/runs/12417681586/job/34669169369?pr=3147#step:8:2182
```
IoUringTest > ioUringIsAvailableOnLinux(boolean) > ioUringIsAvailableOnLinux(boolean) [2] noOffloading=true FAILED
    java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
        at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:58)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/actions/runs/14176571447/job/39712792656?pr=3221

```
> Task :servicetalk-http-netty:test

IoUringTest > ioUringIsAvailableOnLinux(boolean) > ioUringIsAvailableOnLinux(boolean) [1] noOffloading=false FAILED
    java.util.concurrent.TimeoutException: ioUringIsAvailableOnLinux(boolean) timed out after 30 seconds
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
```
