### ISSUE TITLE
ExpectContinueTest failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2638]
macOS OpenJDK17

```
protocol=HTTP_1 useOtherHeadersFactory=false withCL=true

java.lang.AssertionError: Unexpected subscribe to payload body before 100 (Continue)
Expected: is <false>
     but: was <true>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.servicetalk.http.netty.ExpectContinueTest.retryExpectationFailed(ExpectContinueTest.java:526)
```

**Comment by Scottmitch** [comment]
potentially related: https://github.com/apple/servicetalk/pull/2639

**Comment by 82baras** [comment]
If it matters,  i don't see it when I run just that test suite locally. I'm on intel mac.

**Comment by bryce-anderson** [comment]
Another hit: https://github.com/apple/servicetalk/actions/runs/11241179094/job/31252171826?pr=3075#step:8:1100

```
ExpectContinueTest > retryExpectationFailed(HttpProtocol, boolean, boolean) > protocol=HTTP_2 useOtherHeadersFactory=true withCL=true FAILED
    java.lang.AssertionError: Unexpected subscribe to payload body before 100 (Continue)
    Expected: is <false>
         but: was <true>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at io.servicetalk.http.netty.ExpectContinueTest.retryExpectationFailed(ExpectContinueTest.java:526)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/actions/runs/12752422260/job/35541814212?pr=3171

```
ExpectContinueTest > retryExpectationFailed(HttpProtocol, boolean, boolean) > protocol=HTTP_2 useOtherHeadersFactory=false withCL=true FAILED
    java.lang.AssertionError: Unexpected subscribe to payload body before 100 (Continue)
    Expected: is <false>
         but: was <true>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at io.servicetalk.http.netty.ExpectContinueTest.retryExpectationFailed(ExpectContinueTest.java:526)
> Task :servic
```

**Comment by bryce-anderson** [comment]
https://github.com/apple/servicetalk/actions/runs/13168982857/job/36755578122?pr=3185#step:8:1293
```
ExpectContinueTest > retryExpectationFailed(HttpProtocol, boolean, boolean) > protocol=HTTP_2 useOtherHeadersFactory=true withCL=true FAILED
    java.lang.AssertionError: Unexpected subscribe to payload body before 100 (Continue)
    Expected: is <false>
         but: was <true>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at io.servicetalk.http.netty.ExpectContinueTest.retryExpectationFailed(ExpectContinueTest.java:526)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/actions/runs/13958587479/job/39075403249

```
ExpectContinueTest > retryExpectationFailed(HttpProtocol, boolean, boolean) > protocol=HTTP_1 useOtherHeadersFactory=false withCL=false FAILED
    java.lang.AssertionError: Unexpected subscribe to payload body before 100 (Continue)
    Expected: is <false>
         but: was <true>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at io.servicetalk.http.netty.ExpectContinueTest.retryExpectationFailed(ExpectContinueTest.java:526)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/actions/runs/14206191604/job/39804378026?pr=3221

```
ExpectContinueTest > retryExpectationFailed(HttpProtocol, boolean, boolean) > protocol=HTTP_1 useOtherHeadersFactory=true withCL=false FAILED
    java.lang.AssertionError: Unexpected subscribe to payload body before 100 (Continue)
    Expected: is <false>
         but: was <true>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at io.servicetalk.http.netty.ExpectContinueTest.retryExpectationFailed(ExpectContinueTest.java:526)

```
