### ISSUE TITLE
H2PriorKnowledgeFeatureParityTest

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2667]
building https://github.com/apple/servicetalk/pull/2666

https://github.com/apple/servicetalk/actions/runs/5739154791/job/15558314906#step:7:820

```
H2PriorKnowledgeFeatureParityTest > clientConnectionFilterAsyncContext(HttpTestExecutionStrategy, boolean) > clientConnectionFilterAsyncContext(HttpTestExecutionStrategy, boolean) [2] client=NO_OFFLOAD, h2PriorKnowledge=false FAILED
    java.lang.AssertionError: Async errors occurred. See suppressed!
        at io.servicetalk.test.resources.TestUtils.assertNoAsyncErrors(TestUtils.java:58)
        at io.servicetalk.test.resources.TestUtils.assertNoAsyncErrors(TestUtils.java:43)
        at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.clientConnectionFilterAsyncContext(H2PriorKnowledgeFeatureParityTest.java:1304)

H2PriorKnowledgeFeatureParityTest > clientConnectionFilterAsyncContext(HttpTestExecutionStrategy, boolean) > clientConnectionFilterAsyncContext(HttpTestExecutionStrategy, boolean) [3] client=DEFAULT, h2PriorKnowledge=true FAILED
    java.lang.AssertionError: Async errors occurred. See suppressed!
        at io.servicetalk.test.resources.TestUtils.assertNoAsyncErrors(TestUtils.java:58)
        at io.servicetalk.test.resources.TestUtils.assertNoAsyncErrors(TestUtils.java:43)
        at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.clientConnectionFilterAsyncContext(H2PriorKnowledgeFeatureParityTest.java:1304)

H2PriorKnowledgeFeatureParityTest > clientConnectionFilterAsyncContext(HttpTestExecutionStrategy, boolean) > clientConnectionFilterAsyncContext(HttpTestExecutionStrategy, boolean) [4] client=DEFAULT, h2PriorKnowledge=false FAILED
    java.lang.AssertionError: Async errors occurred. See suppressed!
        at io.servicetalk.test.resources.TestUtils.assertNoAsyncErrors(TestUtils.java:58)
        at io.servicetalk.test.resources.TestUtils.assertNoAsyncErrors(TestUtils.java:43)
        at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.clientConnectionFilterAsyncContext(H2PriorKnowledgeFeatureParityTest.java:1304)

```

**Comment by Scottmitch** [comment]
I think this is specific to https://github.com/apple/servicetalk/pull/2666
