### ISSUE TITLE
LingeringRoundRobinLoadBalancerTest failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2677]
local macOS m1 build OpenJDK 17.0.3.7

```
LingeringRoundRobinLoadBalancerTest > expiringAHostDoesntRaceWithConnectionAdding() FAILED
    java.lang.AssertionError: 
    Expected: an instance of io.servicetalk.client.api.NoAvailableHostException
         but: <io.servicetalk.loadbalancer.RoundRobinLoadBalancer$StacklessNoActiveHostException: Failed to pick an active host for test-service. Either all are busy, expired, or unhealthy: [Host{lbDescription=RoundRobinLoadBalancer{id=LingeringRoundRobinLoadBalancerTest@5f65640c, targetResource=test-service}, address=address-1, state=EXPIRED, #connections=1}]> is a io.servicetalk.loadbalancer.RoundRobinLoadBalancer$StacklessNoActiveHostException
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.servicetalk.loadbalancer.LingeringRoundRobinLoadBalancerTest.expiringAHostDoesntRaceWithConnectionAdding(LingeringRoundRobinLoadBalancerTest.java:160)
```

**Comment by Scottmitch** [comment]
potentially related https://github.com/apple/servicetalk/issues/1859

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/runs/16086253855

```
LingeringRoundRobinLoadBalancerTest.expiringAHostDoesntRaceWithConnectionAdding()

java.lang.AssertionError: 
Expected: an instance of io.servicetalk.client.api.NoAvailableHostException
     but: <io.servicetalk.loadbalancer.RoundRobinLoadBalancer$StacklessNoActiveHostException: Failed to pick an active host for test-service. Either all are busy, expired, or unhealthy: [Host{lbDescription=RoundRobinLoadBalancer{id=LingeringRoundRobinLoadBalancerTest@6296e812, targetResource=test-service}, address=address-1, state=EXPIRED, #connections=1}]> is a io.servicetalk.loadbalancer.RoundRobinLoadBalancer$StacklessNoActiveHostException
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.loadbalancer.LingeringRoundRobinLoadBalancerTest.expiringAHostDoesntRaceWithConnectionAdding(LingeringRoundRobinLoadBalancerTest.java:160)

```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2719/checks?check_run_id=17322302398

```
LingeringRoundRobinLoadBalancerTest.expiringAHostDoesntRaceWithConnectionAdding()

java.lang.AssertionError: 
Expected: an instance of io.servicetalk.client.api.NoAvailableHostException
     but: <io.servicetalk.loadbalancer.RoundRobinLoadBalancer$StacklessNoActiveHostException: Failed to pick an active host for test-service. Either all are busy, expired, or unhealthy: [Host{lbDescription=RoundRobinLoadBalancer{id=LingeringRoundRobinLoadBalancerTest@43f5d671, targetResource=test-service}, address=address-1, state=EXPIRED, #connections=1}]> is a io.servicetalk.loadbalancer.RoundRobinLoadBalancer$StacklessNoActiveHostException
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.loadbalancer.LingeringRoundRobinLoadBalancerTest.expiringAHostDoesntRaceWithConnectionAdding(LingeringRoundRobinLoadBalancerTest.java:160)
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/actions/runs/12471261226/job/34807889797?pr=3152

```
> Task :servicetalk-loadbalancer:test

LingeringNewRoundRobinLoadBalancerTest > expiringAHostDoesntRaceWithConnectionAdding() FAILED
    java.lang.AssertionError: 
    Expected: iterable containing [(hasProperty("key", is "address-1") and hasProperty("value", a collection with size <1>))]
         but: no item was (hasProperty("key", is "address-1") and hasProperty("value", a collection with size <1>))
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.servicetalk.loadbalancer.LoadBalancerTestScaffold.assertConnectionCount(LoadBalancerTestScaffold.java:173)
        at io.servicetalk.loadbalancer.LingeringLoadBalancerTest.expiringAHostDoesntRaceWithConnectionAdding(LingeringLoadBalancerTest.java:156)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
```
