### ISSUE TITLE
ConnectionClosedAfterIoExceptionTest failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2685]
https://github.com/apple/servicetalk/pull/2684/checks?check_run_id=16377684587

```
ConnectionClosedAfterIoExceptionTest.test(HttpProtocol) [2]: protocol=HTTP_2

io.netty.channel.socket.ChannelOutputShutdownException: Channel output shutdown
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe.shutdownOutput(AbstractChannel.java:650)
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe.handleWriteError(AbstractChannel.java:953)
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:933)
	at app//io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557)
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.servicetalk.transport.netty.internal.ServiceTalkWireLogger.flush(ServiceTalkWireLogger.java:188)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:197)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.netty.handler.codec.http2.AbstractHttp2StreamChannel.flush0(AbstractHttp2StreamChannel.java:1132)
	at app//io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.flush(AbstractHttp2StreamChannel.java:1078)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
	at app//io.netty.handler.codec.http2.AbstractHttp2StreamChannel.flush(AbstractHttp2StreamChannel.java:438)
	at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.20/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2678/checks?check_run_id=16474632321

```
ConnectionClosedAfterIoExceptionTest.test(HttpProtocol) [2]: protocol=HTTP_2

java.nio.channels.ClosedChannelException
	at io.netty.handler.codec.http2.Http2StreamChannelBootstrap$1.run(Http2StreamChannelBootstrap.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2684/checks?check_run_id=16735617580

```
ConnectionClosedAfterIoExceptionTest.test(HttpProtocol) [2]: protocol=HTTP_2

java.nio.channels.ClosedChannelException
	at io.netty.handler.codec.http2.Http2StreamChannelBootstrap$1.run(Http2StreamChannelBootstrap.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2684/checks?check_run_id=17275743063

```
ConnectionClosedAfterIoExceptionTest.test(HttpProtocol) [2]: protocol=HTTP_2

io.servicetalk.loadbalancer.RoundRobinLoadBalancer$StacklessConnectionRejectedException: Newly created connection IdleTimeoutConnectionFilterImpl[300000 ms]([id: 0x3e2e9922, L:/127.0.0.1:54056 ! R:127.0.0.1/127.0.0.1:43739]) for 127.0.0.1:43739 was rejected by the selection filter.
	at io.servicetalk.loadbalancer.RoundRobinLoadBalancer.selectConnection0(...)(Unknown Source)
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/2684/checks?check_run_id=17327389232

```
ConnectionClosedAfterIoExceptionTest.test(HttpProtocol) [2]: protocol=HTTP_2

java.nio.channels.ClosedChannelException
	at io.netty.handler.codec.http2.Http2StreamChannelBootstrap$1.run(Http2StreamChannelBootstrap.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
