### ISSUE TITLE
JavaNetSoTimeoutHttpConnectionFilterTest failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#2687]
https://github.com/apple/servicetalk/pull/2678/checks?check_run_id=16474632816

```
JavaNetSoTimeoutHttpConnectionFilterTest.noTimeout(boolean, boolean, boolean) [5]: expectContinue=true withServerDelays=false withZeroTimeout=false

java.util.concurrent.TimeoutException: noTimeout(boolean, boolean, boolean) timed out after 30 seconds
...
	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
		at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.concurrent.api.internal.BlockingUtils.blockingInvocation(BlockingUtils.java:70)
		at io.servicetalk.http.api.BlockingRequestUtils.request(BlockingRequestUtils.java:29)
		at io.servicetalk.http.api.StreamingHttpClientToBlockingHttpClient.request(StreamingHttpClientToBlockingHttpClient.java:61)
		at io.servicetalk.http.netty.JavaNetSoTimeoutHttpConnectionFilterTest.noTimeout(JavaNetSoTimeoutHttpConnectionFilterTest.java:167)
```

related to https://github.com/apple/servicetalk/issues/2641

**Comment by Scottmitch** [comment]
```
JavaNetSoTimeoutHttpConnectionFilterTest.noTimeout(boolean, boolean, boolean) [5]: expectContinue=true withServerDelays=false withZeroTimeout=false

java.util.concurrent.TimeoutException: noTimeout(boolean, boolean, boolean) timed out after 30 seconds

	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.concurrent.api.internal.BlockingUtils.blockingInvocation(BlockingUtils.java:70)
		at io.servicetalk.http.api.BlockingRequestUtils.request(BlockingRequestUtils.java:29)
		at io.servicetalk.http.api.StreamingHttpClientToBlockingHttpClient.request(StreamingHttpClientToBlockingHttpClient.java:61)
		at io.servicetalk.http.netty.JavaNetSoTimeoutHttpConnectionFilterTest.noTimeout(JavaNetSoTimeoutHttpConnectionFilterTest.java:167)
	
```

**Comment by bryce-anderson** [comment]
Hit again in https://github.com/apple/servicetalk/pull/2737.

**Comment by tkountis** [comment]
https://github.com/apple/servicetalk/pull/2917/checks?check_run_id=24841951793

```
 JavaNetSoTimeoutHttpConnectionFilterTest.noTimeout(boolean, boolean, boolean) [5]: expectContinue=true withServerDelays=false withZeroTimeout=false

java.util.concurrent.TimeoutException: noTimeout(boolean, boolean, boolean) timed out after 30 seconds

at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
		at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:94)
		at io.servicetalk.concurrent.api.internal.BlockingUtils.blockingInvocation(BlockingUtils.java:70)
		at io.servicetalk.http.api.BlockingRequestUtils.request(BlockingRequestUtils.java:29)
		at io.servicetalk.http.api.StreamingHttpClientToBlockingHttpClient.request(StreamingHttpClientToBlockingHttpClient.java:61)
		at io.servicetalk.http.netty.JavaNetSoTimeoutHttpConnectionFilterTest.noTimeout(JavaNetSoTimeoutHttpConnectionFilt
```

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/actions/runs/9942850815/job/27465285607?pr=3005

```
JavaNetSoTimeoutHttpConnectionFilterTest > noTimeout(boolean, boolean, boolean) > noTimeout(boolean, boolean, boolean) [5]: expectContinue=true withServerDelays=false withZeroTimeout=false FAILED
    java.util.concurrent.TimeoutException: noTimeout(boolean, boolean, boolean) timed out after 30 seconds
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
        at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:58)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
```
