### ISSUE TITLE
flaky test: DefaultDnsClientTest.testQueryTimeout(RecordType) [3] recordType=SRV

### ISSUE THREAD

**Issue by bryce-anderson** [apple/servicetalk#2928]
```
java.lang.AssertionError: 
Expected: a value equal to or greater than <500000000L>
     but: <498157800L> was less than <500000000L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.servicetalk.dns.discovery.netty.DefaultDnsClientTest.testTimeout(DefaultDnsClientTest.java:1277)
	at io.servicetalk.dns.discovery.netty.DefaultDnsClientTest.testQueryTimeout(DefaultDnsClientTest.java:1220)
```
https://github.com/apple/servicetalk/pull/2926/checks?check_run_id=24925458933

**Comment by bryce-anderson** [comment]
Looks like the new DNS timeout tests (add [here](https://github.com/apple/servicetalk/pull/2908)) are flaky. The use of `System.nanoTime()` doesn't guarantee that nanosecond resolution and it looks like we're falling pray to that noise.

**Comment by bryce-anderson** [comment]
Another one: https://github.com/apple/servicetalk/actions/runs/9081908523/job/24956956453?pr=2925#step:7:1152
```
DefaultDnsClientTest > testResolutionTimeout(RecordType) > testResolutionTimeout(RecordType) [3] recordType=SRV FAILED
    java.lang.AssertionError: 
    Expected: a value equal to or greater than <500000000L>
         but: <499693602L> was less than <500000000L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.servicetalk.dns.discovery.netty.DefaultDnsClientTest.testTimeout(DefaultDnsClientTest.java:1277)
        at io.servicetalk.dns.discovery.netty.DefaultDnsClientTest.testResolutionTimeout(DefaultDnsClientTest.java:1226)
```
