### ISSUE TITLE
TrafficResilienceHttpServiceFilterTest. testStopAcceptingConnections failure

### ISSUE THREAD

**Issue by bryce-anderson** [apple/servicetalk#3076]
https://github.com/apple/servicetalk/actions/runs/11243485510/job/31259473870#step:8:1980
```
TrafficResilienceHttpServiceFilterTest > testStopAcceptingConnections(Protocol) > [1] H1 FAILED
    java.util.concurrent.ExecutionException: io.servicetalk.client.api.ConnectTimeoutException: Failed to connect: /127.0.0.1:44983 (localAddress: null)
        at io.servicetalk.concurrent.api.SourceToFuture.reportGet(SourceToFuture.java:134)
        at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:103)
        at io.servicetalk.traffic.resilience.http.TrafficResilienceHttpServiceFilterTest.testStopAcceptingConnections(TrafficResilienceHttpServiceFilterTest.java:193)

        Caused by:
        io.servicetalk.client.api.ConnectTimeoutException: Failed to connect: /127.0.0.1:44983 (localAddress: null)
            at app//io.servicetalk.tcp.netty.internal.TcpConnector$2$1.lambda$connect$0(TcpConnector.java:152)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
            at app//io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
            at app//io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
            at app//io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
            at app//io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:616)
            at app//io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
            at app//io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
            at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
            at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
            at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
            at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
            at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
            at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)

            Caused by:
            io.netty.channel.ConnectTimeoutException: connection timed out after 2000 ms: /127.0.0.1:44983
                at app//io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:615)
                ... 10 more
```

**Comment by bryce-anderson** [comment]
Provisionally closing.

**Comment by idelpivnitskiy** [comment]
https://github.com/apple/servicetalk/actions/runs/11832142064/job/32968458640?pr=3104

```
TrafficResilienceHttpServiceFilterTest > testStopAcceptingConnections(boolean, String) > testStopAcceptingConnections(boolean, String) [3] dryRun=false,protocol=h1 FAILED
    java.util.concurrent.ExecutionException: io.servicetalk.client.api.ConnectTimeoutException: Failed to connect: /127.0.0.1:38839 (localAddress: null)
        at io.servicetalk.concurrent.api.SourceToFuture.reportGet(SourceToFuture.java:134)
        at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:103)
        at io.servicetalk.traffic.resilience.http.TrafficResilienceHttpServiceFilterTest.testStopAcceptingConnections(TrafficResilienceHttpServiceFilterTest.java:257)

        Caused by:
        io.servicetalk.client.api.ConnectTimeoutException: Failed to connect: /127.0.0.1:38839 (localAddress: null)
            at io.servicetalk.tcp.netty.internal.TcpConnector$2$1.lambda$connect$0(TcpConnector.java:152)
            at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
            at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
            at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
            at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
            at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
            at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
            at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
            at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:616)
            at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
            at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
            at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
            at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
            at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
            at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.lang.Thread.run(Thread.java:750)

            Caused by:
            io.netty.channel.ConnectTimeoutException: connection timed out after 4000 ms: /127.0.0.1:38839
                at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:615)
                ... 10 more
```

**Comment by bryce-anderson** [comment]
https://github.com/apple/servicetalk/actions/runs/11849584912/job/33023082080?pr=3107#step:8:2188
```
TrafficResilienceHttpServiceFilterTest > testStopAcceptingConnections(boolean, String) > testStopAcceptingConnections(boolean, String) [3] dryRun=false,protocol=h1 FAILED
    java.util.concurrent.ExecutionException: io.servicetalk.client.api.ConnectTimeoutException: Failed to connect: /127.0.0.1:39327 (localAddress: null)
        at io.servicetalk.concurrent.api.SourceToFuture.reportGet(SourceToFuture.java:134)
        at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:103)
        at io.servicetalk.traffic.resilience.http.TrafficResilienceHttpServiceFilterTest.testStopAcceptingConnections(TrafficResilienceHttpServiceFilterTest.java:257)

        Caused by:
        io.servicetalk.client.api.ConnectTimeoutException: Failed to connect: /127.0.0.1:39327 (localAddress: null)
            at app//io.servicetalk.tcp.netty.internal.TcpConnector$2$1.lambda$connect$0(TcpConnector.java:152)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
            at app//io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
            at app//io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
            at app//io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
            at app//io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:616)
            at app//io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
            at app//io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
            at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
            at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
            at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
            at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
            at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
            at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)

            Caused by:
            io.netty.channel.ConnectTimeoutException: connection timed out after 4000 ms: /127.0.0.1:39327
                at app//io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:615)
                ... 10 more
```

**Comment by bryce-anderson** [comment]
If it happens again, we can reopen it.
