### ISSUE TITLE
ZipkinPublisherTest.testThriftRoundTrip test failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#899]
https://ci.servicetalk.io/job/servicetalk-java8-prb/904/testReport/junit/io.servicetalk.opentracing.zipkin.publisher/ZipkinPublisherTest/testThriftRoundTrip/
```
Error Message

org.junit.runners.model.TestTimedOutException: test timed out after 90000 milliseconds
Stacktrace

org.junit.runners.model.TestTimedOutException: test timed out after 90000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
	at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
	at io.servicetalk.opentracing.zipkin.publisher.ZipkinPublisherTest.testRoundTrip(ZipkinPublisherTest.java:143)
	at io.servicetalk.opentracing.zipkin.publisher.ZipkinPublisherTest.testThriftRoundTrip(ZipkinPublisherTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:171)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Standard Output

"/127.0.0.1:38356 to /127.0.0.1:42084 workers Thread 2" #12 waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5779cd9d
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Native Method)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
	  at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:320)
	  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	  at java.lang.Thread.run(Thread.java:748)

	  Number of locked synchronizers = 1
	  - java.util.concurrent.ThreadPoolExecutor$Worker@67205a84

"/127.0.0.1:38356 to /127.0.0.1:42084 workers Thread 3" #13 runnable (in native)
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	  at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	  - locked sun.nio.ch.Util$3@61d52535
	  - locked java.util.Collections$UnmodifiableSet@4a2cd26b
	  - locked sun.nio.ch.EPollSelectorImpl@28fe26fc
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	  at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:182)
	  at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	  at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	  at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
	  at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:81)
	  at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:64)
	  at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	  at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	  at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:268)
	  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	  at java.lang.Thread.run(Thread.java:748)

	  Number of locked synchronizers = 1
	  - java.util.concurrent.ThreadPoolExecutor$Worker@2a17b7b6

"Finalizer" #3 waiting on java.lang.ref.ReferenceQueue$Lock@1f4da6ca
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Native Method)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 waiting on java.lang.ref.Reference$Lock@33de90c2
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Native Method)
	  at java.lang.Object.wait(Object.java:502)
	  at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"Signal Dispatcher" #4 runnable
  java.lang.Thread.State: RUNNABLE

"Test worker" #11 runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.management.ThreadImpl.dumpThreads0(Native Method)
	  at sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:448)
	  at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement.dumpAllStacks(ServiceTalkTestTimeout.java:187)
	  at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement.getResult(ServiceTalkTestTimeout.java:147)
	  at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement.evaluate(ServiceTalkTestTimeout.java:127)
	  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	  at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	  at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	  at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	  at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	  at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	  at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	  at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	  at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	  at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	  at java.lang.Thread.run(Thread.java:748)

	  Number of locked synchronizers = 1
	  - java.util.concurrent.ThreadPoolExecutor$Worker@6f1fba17

"Time-limited test" #29 waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@21cbc678
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Native Method)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
	  at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
	  at io.servicetalk.opentracing.zipkin.publisher.ZipkinPublisherTest.testRoundTrip(ZipkinPublisherTest.java:143)
	  at io.servicetalk.opentracing.zipkin.publisher.ZipkinPublisherTest.testThriftRoundTrip(ZipkinPublisherTest.java:94)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	  at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:171)
	  at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:163)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	  at java.lang.Thread.run(Thread.java:748)

"main" #1 waiting on java.util.concurrent.CountDownLatch$Sync@6a4e9983
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Native Method)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	  at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:72)
	  at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:46)
	  at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:91)
	  at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:34)
	  at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:136)
	  at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:69)
	  at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:68)
	  at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:73)

"nioEventLoopGroup-8-1" #31 runnable (in native)
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	  at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	  - locked io.netty.channel.nio.SelectedSelectionKeySet@46d0d1cd
	  - locked java.util.Collections$UnmodifiableSet@69d8414d
	  - locked sun.nio.ch.EPollSelectorImpl@2398351f
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:748)
```

**Comment by idelpivnitskiy** [comment]
This test didn't fail for a long time and we did a rework of `ZipkinPublisher` in #1001. Closing this for now.
