### ISSUE TITLE
Flaky tests: H2PriorKnowledgeFeatureParityTest.fullDuplexMode[client=CACHED, h2PriorKnowledge=true] - AssertionError

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#911]
Failed with JDK11, can not reproduce locally:

```
Regression
io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.fullDuplexMode[client=CACHED, h2PriorKnowledge=true]

Error Message
java.lang.AssertionError
Stacktrace
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at io.servicetalk.http.netty.H2PriorKnowledgeFeatureParityTest.fullDuplexMode(H2PriorKnowledgeFeatureParityTest.java:692)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:171)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:163)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://ci.servicetalk.io/job/servicetalk-java11-prb/928/testReport/junit/io.servicetalk.http.netty/H2PriorKnowledgeFeatureParityTest/fullDuplexMode_client_CACHED__h2PriorKnowledge_true_/

**Comment by idelpivnitskiy** [comment]
This test didn't fail for a long time. Closing for now.
